### ISSUE TITLE
Materialize 0.97.0

### ISSUE THREAD

**Issue by mchiareli** [webjars/materializecss#4]
Can you please release a version for materialize 0.97.0

**Comment by mchiareli** [comment]
I don't see this version on webjars website.

Which version should I use in my dependencies?

Thanks

Wysłane z iPhone'a

**Comment by jamesward** [comment]
It takes a few hours for it to show up there.  The version is `0.97.0`.

**Comment by mchiareli** [comment]
got it, thanks.
